Areas/Contabilidade/Controllers/LancamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using gestaoContadorcomvc.Areas.Contabilidade.Models;
using gestaoContadorcomvc.Areas.Contabilidade.Models.ViewModel;
using gestaoContadorcomvc.Models;
using gestaoContadorcomvc.Models.Autenticacao;
using gestaoContadorcomvc.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace gestaoContadorcomvc.Areas.Contabilidade.Controllers
{
    [Area("Contabilidade")]
    [Route("Contabilidade/[controller]/[action]")]
    [Authorize(Roles = "Contabilidade")]
    public class LancamentoController : Controller
    {
        // GET: LancamentoController
        public ActionResult Index()
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);
            Conta contexto = new Conta();
            contexto = contexto.contextoCliente(Convert.ToInt32(user.usuario_ultimoCliente));

            Lancamento lancamento = new Lancamento();
            vm_lancamento vm_lanc = new vm_lancamento();
            vm_lanc.lancamentos = lancamento.listarLancamentosLimit(user.usuario_id, contexto.conta_id, user.usuario_conta_id, 25);
            vm_lanc.user = user;

            return View(vm_lanc);
        }        

        // GET: LancamentoController/Create
        public ActionResult Create()
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);
            Conta contexto = new Conta();
            contexto = contexto.contextoCliente(Convert.ToInt32(user.usuario_ultimoCliente));

            Config_contador_cliente config = new Config_contador_cliente();
            vm_ConfigContadorCliente vm_config = new vm_ConfigContadorCliente();
            vm_config = config.buscaCCC(user.usuario_id, contexto.conta_id, user.usuario_conta_id);

            Lancamento lancamento = new Lancamento();
            vm_lancamento vm_lanc = new vm_lancamento();
            vm_lanc.lancamentos = lancamento.listarLancamentosLimit(user.usuario_id, contexto.conta_id, user.usuario_conta_id, 3);
            vm_lanc.user = user;
            vm_lanc.vm_config = vm_config;

            if(config.ccc_planoContasVigente != "0")
            {
                Selects select = new Selects();
                ViewBag.planoContas = select.getPlanoContas(Convert.ToInt32(vm_config.ccc_planoContasVigente)).Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled });
            }            

            return View(vm_lanc);
        }

        // POST: LancamentoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {            
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["novoLancamento"] = "Erro no preenchimento das informações do formulário!";

                    return RedirectToAction(nameof(Create));
                }

                Usuario usuario = new Usuario();
                Vm_usuario user = new Vm_usuario();
                user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);
                Conta contexto = new Conta();
                contexto = contexto.contextoCliente(Convert.ToInt32(user.usuario_ultimoCliente));

                Lancamento lancamento = new Lancamento();
                TempData["novoLancamento"] = lancamento.cadastrarLancamento(user.usuario_id, contexto.conta_id, user.usuario_conta_id, "Lançamento Contábil", Convert.ToDateTime(collection["lancamento_data"]), collection["lancamento_valor"], collection["lancamento_debito_conta_id"], collection["lancamento_credito_conta_id"], collection["lancamento_historico"]);

                Config_contador_cliente config = new Config_contador_cliente();
                vm_ConfigContadorCliente vm_config = new vm_ConfigContadorCliente();
                vm_config = config.buscaCCC(user.usuario_id, contexto.conta_id, user.usuario_conta_id);

                vm_lancamento vm_lanc = new vm_lancamento();
                vm_lanc.lancamentos = lancamento.listarLancamentosLimit(user.usuario_id, contexto.conta_id, user.usuario_conta_id, 3);
                vm_lanc.user = user;
                vm_lanc.vm_config = vm_config;

                if (config.ccc_planoContasVigente != "0")
                {
                    Selects select = new Selects();
                    ViewBag.planoContas = select.getPlanoContas(Convert.ToInt32(vm_config.ccc_planoContasVigente)).Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled });
                }

                return View(vm_lanc);
            }
            catch
            {
                TempData["novoLancamento"] = "Erro ao registrar o lançamento contábil. Tente novamente. Se persistir entre em contato com o suporte!";

                return RedirectToAction(nameof(Create));
            }
        }

        // GET: LancamentoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LancamentoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LancamentoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LancamentoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/LancamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using gestaoContadorcomvc.Models;
using gestaoContadorcomvc.Models.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace gestaoContadorcomvc.Controllers
{
    public class LancamentoController : Controller
    {
        // GET: LancamentoController
        public ActionResult Index()
        {
            List<Vm_lancamento> lancamentos = new List<Vm_lancamento>();
            lancamentos.Add(new Vm_lancamento
            {
                lancamento_id = 1,
                lancamento_data = new DateTime(2020,09,14),
                lancamento_debito_descricao = "01.1.1.01.001 - Caixa",
                lancamento_credito_descricao = "04.2.1.03.001 - Aluguel",
                lancamento_valor = Convert.ToDecimal("835.9"),
                lancamento_tipo = "Lançamento Contábil"
            });
            lancamentos.Add(new Vm_lancamento
            {
                lancamento_id = 2,
                lancamento_data = new DateTime(2020, 09, 14),
                lancamento_debito_descricao = "01.1.1.01.001 - Caixa",
                lancamento_credito_descricao = "04.2.1.03.004 - Internet",
                lancamento_valor = Convert.ToDecimal("160.32"),
                lancamento_tipo = "Lançamento Contábil"
            });
            lancamentos.Add(new Vm_lancamento
            {
                lancamento_id = 3,
                lancamento_data = new DateTime(2020, 09, 14),
                lancamento_debito_descricao = "01.1.1.01.001 - Caixa",
                lancamento_credito_descricao = "04.2.1.03.007 - Material de limpeza",
                lancamento_valor = Convert.ToDecimal("259.60"),
                lancamento_tipo = "Gestão de Compras"
            });
            lancamentos.Add(new Vm_lancamento
            {
                lancamento_id = 4,
                lancamento_data = new DateTime(2020, 09, 14),
                lancamento_debito_descricao = "01.1.1.01.001 - Caixa",
                lancamento_credito_descricao = "04.2.1.03.009 - Manutenção e reparos",
                lancamento_valor = Convert.ToDecimal("532.5"),
                lancamento_tipo = "Gestão de Compras"
            });
            lancamentos.Add(new Vm_lancamento
            {
                lancamento_id = 5,
                lancamento_data = new DateTime(2020, 09, 14),
                lancamento_debito_descricao = "01.1.1.01.001 - Caixa",
                lancamento_credito_descricao = "04.2.1.03.003 - Energia elétrica",
                lancamento_valor = Convert.ToDecimal("168.50"),
                lancamento_tipo = "Gestão de Compras"
            });

            ViewData["bread"] = "Lançamento Contábil";

            return View(lancamentos);
        }

        // GET: LancamentoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LancamentoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LancamentoController/Create
        [HttpPost]       
        public ActionResult Create(IFormCollection collection)
        {
            //lanc dados
            try
            {


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LancamentoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LancamentoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LancamentoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LancamentoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Areas/Contabilidade/Views/Lancamento/Create.cshtml
@model gestaoContadorcomvc.Areas.Contabilidade.Models.ViewModel.vm_lancamento
@{
    ViewData["Title"] = "Lançamento Contábil";
    Layout = "~/Areas/Contabilidade/Views/Shared/_Layout.cshtml";
}
<style>
    .col-list-rigth {
        width: 90px;
        text-align: right;
    }

    .check-list-label {
        display: none;
    }

    .col-list-body {
        width: calc(100%);
    }

    a {
        cursor: pointer;
    }

    .line-list {
        border: 0px;
    }

    .ultimosLancamentos {
        font-size: 12px;
        font-family: sans-serif;
    }
</style>



<h2>Novo Lançamento Contábil</h2>
<hr class="hrLine" />

@{
    if (TempData["novoLancamento"] != null && TempData["novoLancamento"].ToString().Contains("sucesso"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Sucesso!</strong> @TempData["novoLancamento"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    if (TempData["novoLancamento"] != null && TempData["novoLancamento"].ToString().Contains("Erro"))
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Erro!</strong> @TempData["novoLancamento"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

@{
    if (Model.vm_config.ccc_planoContasVigente != "0")
    {
        <form id="formLancamentoContabil" asp-area="Contabilidade" asp-controller="Lancamento" asp-action="Create">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label asp-for="lancamento_debito_conta_id" class="control-label"></label>
                        @*<select asp-items="@ViewBag.planoContas" value="@TempData["lancamento_debito_conta_id"]" id="lancamento_debito_conta_id" name="lancamento_debito_conta_id" class="form-control js_example_basic_single" style="width: 100%;" autofocus></select>*@
                        <input type="text" id="conta_debito" class="form-control" onkeydown="consultaContasContabeis(this.id, 'debito', this.value)" />
                        <span class="text-info" style="font-size:12px"><strong>Conta nível: </strong><span id="nivel_debito"></span></span><br/>
                        <span asp-validation-for="lancamento_debito_conta_id" class="text-danger"></span>
                        <span asp-validation-for="conta_debito_nivel" class="text-danger"></span>
                        <input type="hidden" asp-for="lancamento_debito_conta_id" id="lancamento_debito_conta_id" name="lancamento_debito_conta_id" value="0" />
                        <input type="hidden" asp-for="conta_debito_nivel" id="conta_debito_nivel" name="conta_debito_nivel" value="0" />
                    </div>
                </div>                
            </div>           
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label asp-for="lancamento_credito_conta_id" class="control-label"></label>
                        <input id="conta_credito" class="form-control" onkeydown="consultaContasContabeis(this.id, 'credito', this.value)" />
                        <span class="text-info" style="font-size:12px"><strong>Conta nível: </strong><span id="nivel_credito"></span></span><br />
                        <span asp-validation-for="lancamento_credito_conta_id" class="text-danger"></span>
                        <span asp-validation-for="conta_credito_nivel" class="text-danger"></span>
                        <input type="hidden" asp-for="lancamento_credito_conta_id" name="lancamento_credito_conta_id" id="lancamento_credito_conta_id" value="0" />
                        <input type="hidden" asp-for="conta_credito_nivel" id="conta_credito_nivel" name="conta_credito_nivel" value="0" />
                    </div>
                </div>   
            </div>
                @*<div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label asp-for="lancamento_participante_credito" class="control-label"></label>
                    <input asp-for="lancamento_participante_credito" class="form-control" disabled="disabled" />
                    <span asp-validation-for="lancamento_participante_credito" class="text-danger"></span>
                </div>
            </div>
        </div>*@
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="lancamento_data" class="control-label"></label>
                            <input type="text" asp-for="lancamento_data" id="lancamento_data_create" class="form-control datepicker" />
                            <span asp-validation-for="lancamento_data" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="lancamento_valor" class="control-label"></label>
                            <input type="number" asp-for="lancamento_valor" step="0.01" id="lancamento_valor_create" class="form-control" onblur="formatValor(this.id, this.value, '2')" />
                            <span asp-validation-for="lancamento_valor" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                            <label asp-for="lancamento_historico" class="control-label"></label>
                            <textarea asp-for="lancamento_historico" class="form-control" rows="3"></textarea>
                            <span asp-validation-for="lancamento_historico" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-info">Gravar</button>
                <a class="btn btn-secondary" asp-area="Contabilidade" asp-controller="Lancamento" asp-action="index">Voltar</a>
</form>

        <div class="list-header">
            <hr class="hrLine" />
            <h6>Últimos lançamentos</h6>

            <div class="line-list">
                <div class="col-list-left">
                    <input class="check-list-input" type="checkbox" id="cp_todas">
                    <label class="check-list-label" for="cp_todas"></label>
                </div>
                <div class="col-list-body">
                    <div class="row">
                        <div class="col-12 col-md-3"><strong>Débito</strong></div>
                        <div class="col-12 col-md-3"><strong>Crédito</strong></div>
                        <div class="col-12 col-md-2"><strong>Data</strong></div>
                        <div class="col-12 col-md-2"><strong>Valor</strong></div>
                        <div class="col-12 col-md-2"><strong>Histórico</strong></div>
                    </div>
                </div>
                @*<div class="col-list-rigth" style="padding-right: 10px;">
                        <span><strong>Ações</strong></span>
                    </div>*@
            </div>
            <div class="ultimosLancamentos">
                @{
                    foreach (var item in Model.lancamentos)
                    {
                        <div class="line-list">
                            <div class="col-list-left">
                                <input class="check-list-input" type="checkbox" id="cp_todas">
                                <label class="check-list-label" for="cp_todas"></label>
                            </div>
                            <div class="col-list-body">
                                <div class="row">
                                    <div class="col-12 col-md-3">@item.lancamento_debito_classificacao - @item.lancamento_debito_nome</div>
                                    <div class="col-12 col-md-3">@item.lancamento_credito_classificacao - @item.lancamento_credito_nome</div>
                                    <div class="col-12 col-md-2">@item.lancamento_data.ToString("d")</div>
                                    <div class="col-12 col-md-2">@item.lancamento_valor.ToString("N")</div>
                                    <div class="col-12 col-md-2">@item.lancamento_historico</div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    }
    else
    {
        <p>Cliente não possui um plano de contas configurado. Para realizar lançamento configure um plano de contas!</p>
    }
}

Areas/Contabilidade/Views/Lancamento/Index.cshtml
@model gestaoContadorcomvc.Areas.Contabilidade.Models.ViewModel.vm_lancamento
@{
    ViewData["Title"] = "Lançamento Contábil";
    Layout = "~/Areas/Contabilidade/Views/Shared/_Layout.cshtml";
}

<style>
    .col-list-rigth {
        width: 90px;
        text-align: right;
    }

    .check-list-label {
        display: none;
    }

    .col-list-body {
        width: calc(100% - 90px);
    }

    a {
        cursor: pointer;
    }

    .line-list {
        border: 0px;
    }

    .ultimosLancamentos {
        font-size: 12px;
        font-family: sans-serif;
    }
</style>

<h2>Lançamento Contábil</h2>
<div class="btn-tools">
    <div class="row">
        <div class="col-10" style="text-align:left">            
            @{
                if (Model.user.Role == "adm" || Model.user._permissoes.planoContasCreate)
                {
                        <a asp-area="Contabilidade" asp-controller="Lancamento" asp-action="Create">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                            </svg>
                            <span>Novo Lançamento</span>
                        </a>
                }
            }

        </div>
        <div class="col-2" style="text-align:right">
            <a onClick="window.print()">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-printer" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11 2H5a1 1 0 0 0-1 1v2H3V3a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v2h-1V3a1 1 0 0 0-1-1zm3 4H2a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h1v1H2a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1z" />
                    <path fill-rule="evenodd" d="M11 9H5a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1zM5 8a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H5z" />
                    <path d="M3 7.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z" />
                </svg>
            </a>
        </div>
    </div>
</div>
<hr class="hrLine" />

@{
    if (TempData["novoLancamento"] != null && TempData["novoLancamento"].ToString().Contains("Sucesso"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Erro!</strong> @TempData["novoLancamento"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    if (TempData["novoLancamento"] != null && TempData["novoLancamento"].ToString().Contains("Erro"))
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Erro!</strong> @TempData["novoLancamento"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<div class="list-header">
    <div class="line-list">
        <div class="col-list-left">
            <input class="check-list-input" type="checkbox" id="cp_todas">
            <label class="check-list-label" for="cp_todas"></label>
        </div>
        <div class="col-list-body">
            <div class="row">
                <div class="col-12 col-md-3"><strong>Débito</strong></div>
                <div class="col-12 col-md-3"><strong>Crédito</strong></div>
                <div class="col-12 col-md-2"><strong>Data</strong></div>
                <div class="col-12 col-md-2"><strong>Valor</strong></div>
                <div class="col-12 col-md-2"><strong>Histórico</strong></div>
            </div>
        </div>
        <div class="col-list-rigth" style="padding-right: 10px;">
            <span><strong>Ações</strong></span>
        </div>
    </div>
</div>
@{
    foreach (var item in Model.lancamentos)
    {
        <div class="line-list">
            <div class="col-list-left">
                <input class="check-list-input" type="checkbox" id="cp_todas">
                <label class="check-list-label" for="cp_todas"></label>
            </div>
            <div class="col-list-body">
                <div class="row">
                    <div class="col-12 col-md-2 line_list_title_mobile"><strong>Débito: </strong>@item.lancamento_debito_classificacao - @item.lancamento_debito_nome</div>
                    <div class="col-12 col-md-2 line_list_title_mobile"><strong>Crédito: </strong>@item.lancamento_credito_classificacao - @item.lancamento_credito_nome</div>
                    <div class="col-12 col-md-2 line_list_title_mobile"><strong>Data: </strong>@item.lancamento_data.ToString("d")</div>
                    <div class="col-12 col-md-2 line_list_title_mobile"><strong>Valor: </strong>@item.lancamento_valor.ToString("N")</div>
                    <div class="col-12 col-md-4 line_list_title_mobile"><strong>Histórico: </strong>@item.lancamento_historico</div>

                    <div class="col-12 col-md-3 line_list_title_full">@item.lancamento_debito_classificacao - @item.lancamento_debito_nome</div>
                    <div class="col-12 col-md-3 line_list_title_full">@item.lancamento_credito_classificacao - @item.lancamento_credito_nome</div>
                    <div class="col-12 col-md-2 line_list_title_full">@item.lancamento_data.ToString("d")</div>
                    <div class="col-12 col-md-2 line_list_title_full">@item.lancamento_valor.ToString("N")</div>
                    <div class="col-12 col-md-2 line_list_title_full">@item.lancamento_historico</div>
                </div>
            </div>
            <div class="col-list-rigth" style="padding-right: 10px;">
                @{
                    if (Model.user.Role == "adm" || Model.user._permissoes.planoContasEdit)
                    {
                        <a class="edit" data-id="@item.lancamento_debito_conta_id">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                            </svg>
                        </a>
                    }
                    if (Model.user.Role == "adm" || Model.user._permissoes.planoContasDelete)
                    {
                        <a class="delete" data-id="@item.lancamento_debito_conta_id">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                            </svg>
                        </a>
                    }
                }
            </div>
        </div>
    }
}