Areas/Contabilidade/Controllers/CCOPlanoCategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using gestaoContadorcomvc.Areas.Contabilidade.Models;
using gestaoContadorcomvc.Areas.Contabilidade.Models.ViewModel;
using gestaoContadorcomvc.Filtros;
using gestaoContadorcomvc.Models;
using gestaoContadorcomvc.Models.Autenticacao;
using gestaoContadorcomvc.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace gestaoContadorcomvc.Areas.Contabilidade.Controllers
{
    [Area("Contabilidade")]
    [Route("Contabilidade/[controller]/[action]")]    
    [Authorize(Roles = "Contabilidade")]
    public class CCOPlanoCategoriasController : Controller
    {
        [Autoriza(permissao = "planoCategoriasCreate")]
        public ActionResult Details(int id, int planoContas_id, int planoCategorias_id)
        {
            TempData["planoCategorias_id"] = planoCategorias_id;
            TempData["planoContas_id"] = planoContas_id;

            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);            

            Categoria_contaonline cco = new Categoria_contaonline();
            vm_categoria_contaonline vm_cco = new vm_categoria_contaonline();
            vm_cco = cco.buscarVinculo(user.usuario_conta_id, user.usuario_id, id);

            return View(vm_cco);
        }

        [Autoriza(permissao = "planoCategoriasCreate")]
        public ActionResult Create(int categoria_id, int planoContas_id, int planoCategorias_id)
        {
            TempData["planoCategorias_id"] = planoCategorias_id;
            TempData["planoContas_id"] = planoContas_id;

            Categoria categoria = new Categoria();
            Vm_categoria vm_Categoria = new Vm_categoria();
            vm_Categoria = categoria.buscaCategoria(categoria_id);

            vm_categoria_contaonline vm_cco = new vm_categoria_contaonline();
            vm_cco.cco_plano_id = planoContas_id;
            vm_cco.cco_categoria_id = categoria_id;
            vm_cco.categoria_nome = vm_Categoria.categoria_nome;

            Selects select = new Selects();
            ViewBag.planoContas = select.getPlanoContas(planoContas_id).Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled });

            return View(vm_cco);
        }

        // POST: CCOController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);            

            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["retornoCCO"] = "Erro! Há informações incorretas no formulário de vinculação de conta on line!";

                    return RedirectToAction("Index", "CategoriasPlano", new { @pc_id = collection["planoCategorias_id"], @planoContas_id = collection["planoContas_id"] });
                }

                Categoria_contaonline cco = new Categoria_contaonline();

                TempData["retornoCCO"] = cco.vinculacaoCCO(user.usuario_id, user.usuario_conta_id, user.usuario_conta_id, collection["cco_plano_id"], collection["cco_ccontabil_id"], collection["cco_categoria_id"]);

                return RedirectToAction("Index", "CategoriasPlano", new { @pc_id = collection["planoCategorias_id"], @planoContas_id = collection["planoContas_id"] });
            }
            catch
            {
                TempData["retornoCCO"] = "Erro! Houve uma falha na vinculação da conta on line. Tente novamente. Se persistir entre em contato com o suporte!";

                return RedirectToAction("Index", "CategoriasPlano", new { @pc_id = collection["planoCategorias_id"], @planoContas_id = collection["planoContas_id"] });
            }
        }

        // POST: CCOController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int cco_id, string cco_plano_id, string cco_categoria_id, string cco_ccontabil_id, int planoContas_id, int planoCategorias_id)
        {
            try
            {
                Usuario usuario = new Usuario();
                Vm_usuario user = new Vm_usuario();
                user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);

                Categoria_contaonline cco = new Categoria_contaonline();

                TempData["retornoCCO"] = cco.desvinculacaoCCO(user.usuario_id, user.usuario_conta_id, user.usuario_conta_id, cco_id, cco_plano_id, cco_ccontabil_id, cco_categoria_id);

                return RedirectToAction("Index", "CategoriasPlano", new { @pc_id = planoCategorias_id, @planoContas_id = planoContas_id });
            }
            catch
            {
                TempData["retornoCCO"] = "Erro! Houve uma falha na desvinculação da conta on line. Tente novamente. Se persistir entre em contato com o suporte!";

                return RedirectToAction("Index", "CategoriasPlano", new { @pc_id = planoCategorias_id, @planoContas_id = planoContas_id });
            }
        }
    }
}

Areas/Contabilidade/Views/CCOPlanoCategorias/Create.cshtml
@model gestaoContadorcomvc.Areas.Contabilidade.Models.ViewModel.vm_categoria_contaonline
@{
    Layout = null;
}
<style>
    #SelectClient + .select2-container .select2-selection--single {
        box-sizing: border-box;
        cursor: pointer;
        display: block;
        height: 38px;
        user-select: none;
        -webkit-user-select: none;
    }

        #SelectClient + .select2-container .select2-selection--single:focus {
            color: #495057;
            background-color: #fff;
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);
        }

    /* line 131 */
    #SelectClient + .select2-container--default .select2-selection--single .select2-selection__rendered {
        color: #444;
        line-height: 38px;
    }

    /* line 139 */
    #SelectClient + .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 38px;
        position: absolute;
        top: 1px;
        right: 1px;
        width: 20px;
    }
</style>

<div class="container">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Víncular Conta on Line</h4>
            </div>
            <form asp-area="Contabilidade" asp-controller="CCOPlanoCategorias" asp-action="Create">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <p>Vincular conta on line a categoria: <strong>@Model.categoria_nome</strong></p>
                        </div>
                    </div>
                    <hr class="hrLine" />
                    @{
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="cco_ccontabil_id" class="control-label"></label>
                                    <select asp-items="@ViewBag.planoContas" value="@TempData["cco_ccontabil_id"]" id="cco_ccontabil_id" name="cco_ccontabil_id" class="form-control js_example_basic_single" style="width: 100%;"></select>
                                    <span asp-validation-for="cco_ccontabil_id" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" asp-for="cco_plano_id" />
                        <input type="hidden" asp-for="cco_categoria_id" />
                        <input type="hidden" name="planoCategorias_id" value='@(TempData["planoCategorias_id"] != null ? @TempData["planoCategorias_id"].ToString() : "")' />
                        <input type="hidden" name="planoContas_id" value='@(TempData["planoContas_id"] != null ? @TempData["planoContas_id"].ToString() : "")' />
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-info">Gravar</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js_example_basic_single').select2({
            width: 'resolve'
        });
    });
</script>

Areas/Contabilidade/Views/CCOPlanoCategorias/Details.cshtml
@model gestaoContadorcomvc.Areas.Contabilidade.Models.ViewModel.vm_categoria_contaonline
@{
    Layout = null;
}
<style>
    #SelectClient + .select2-container .select2-selection--single {
        box-sizing: border-box;
        cursor: pointer;
        display: block;
        height: 38px;
        user-select: none;
        -webkit-user-select: none;
    }

        #SelectClient + .select2-container .select2-selection--single:focus {
            color: #495057;
            background-color: #fff;
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);
        }

    /* line 131 */
    #SelectClient + .select2-container--default .select2-selection--single .select2-selection__rendered {
        color: #444;
        line-height: 38px;
    }

    /* line 139 */
    #SelectClient + .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 38px;
        position: absolute;
        top: 1px;
        right: 1px;
        width: 20px;
    }
</style>

<div class="container">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Conta on Line</h4>
            </div>
            <form asp-area="Contabilidade" asp-controller="CCOPlanoCategorias" asp-action="Delete">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <p>Categoria <strong>@Model.categoria_nome</strong> vinculada a conta on line detalhada abaixo:</p>
                        </div>
                    </div>
                    <hr class="hrLine" />
                    <div class="row">
                        <div class="col-12">
                            <p><strong>Plano de Contas: </strong>@Model.cco_plano_nome</p>
                        </div>
                        <div class="col-12">
                            <p><strong>Conta on line: </strong>@Model.cco_ccontabil_nome</p>
                        </div>
                        <div class="col-12">
                            <p><strong>Classificação: </strong>@Model.cco_ccontabil_classificacao</p>
                        </div>
                    </div>
                </div>
                <input type="hidden" asp-for="cco_id" />
                <input type="hidden" asp-for="cco_plano_id" />
                <input type="hidden" asp-for="cco_ccontabil_id" />
                <input type="hidden" asp-for="cco_categoria_id" />
                <input type="hidden" name="planoCategorias_id" value='@(TempData["planoCategorias_id"] != null ? @TempData["planoCategorias_id"].ToString() : "")' />
                <input type="hidden" name="planoContas_id" value='@(TempData["planoContas_id"] != null ? @TempData["planoContas_id"].ToString() : "")' />
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-danger">Excluir Vínculo</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->    
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

Areas/Contabilidade/Views/CCOPlanoCategorias/Edit.cshtml
@model gestaoContadorcomvc.Areas.Contabilidade.Models.ViewModel.vm_categoria_contaonline
@{
    Layout = null;
}
<style>
    #SelectClient + .select2-container .select2-selection--single {
        box-sizing: border-box;
        cursor: pointer;
        display: block;
        height: 38px;
        user-select: none;
        -webkit-user-select: none;
    }

        #SelectClient + .select2-container .select2-selection--single:focus {
            color: #495057;
            background-color: #fff;
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);
        }

    /* line 131 */
    #SelectClient + .select2-container--default .select2-selection--single .select2-selection__rendered {
        color: #444;
        line-height: 38px;
    }

    /* line 139 */
    #SelectClient + .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 38px;
        position: absolute;
        top: 1px;
        right: 1px;
        width: 20px;
    }
</style>

<div class="container">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Víncular Conta on Line</h4>
            </div>
            <form asp-area="Contabilidade" asp-controller="CCO" asp-action="Edit">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <p>Vincular conta on line a categoria: <strong>@Model.categoria_nome</strong></p>
                        </div>
                    </div>
                    <hr class="hrLine" />
                    @{
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="cco_ccontabil_id" class="control-label"></label>
                                    <select asp-items="@ViewBag.planoContas" value="@TempData["cco_ccontabil_id"]" id="cco_ccontabil_id" name="cco_ccontabil_id" class="form-control js_example_basic_single" style="width: 100%;"></select>
                                    <span asp-validation-for="cco_ccontabil_id" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" asp-for="cco_plano_id" />
                        <input type="hidden" asp-for="cco_categoria_id" />
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-info">Gravar</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js_example_basic_single').select2({
            width: 'resolve'
        });
    });
</script>