Models/ContaPadrao.cs
using gestaoContadorcomvc.Models.Autenticacao;
using gestaoContadorcomvc.Models.SoftwareHouse;
using gestaoContadorcomvc.Models.ViewModel;
using Microsoft.Extensions.Configuration;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace gestaoContadorcomvc.Models
{
    public class ContaPadrao
    {
        public int contaPadrao_id { get; set; }
        public string contaPadrao_classificacao { get; set; }
        public string contaPadrao_descricao { get; set; }
        public string contaPadrao_apelido { get; set; }
        public string contaPadrao_grupo { get; set; }
        public string contaPadrao_tipo { get; set; }
        public int contaPadrao_conta_id { get; set; }
        public string contaPadrao_especie { get; set; }
        public string contaPadrao_natureza { get; set; }
        public int contaPadrao_filhos { get; set; }
        public string contaPadrao_status { get; set; }
        public string contapadrao_tags { get; set; }
        public string contaPadrao_codigoBanco { get; set; }


        /*--------------------------*/
        //Métodos para pegar a string de conexão do arquivo appsettings.json e gerar conexão no MySql.      
        public IConfigurationRoot GetConfiguration()
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            return builder.Build();
        }
        //Método para gerar a conexão
        MySqlConnection conn;
        public ContaPadrao()
        {
            var configuration = GetConfiguration();
            conn = new MySqlConnection(configuration.GetSection("ConnectionStrings").GetSection("conexaocvc").Value);
        }

        //MÉTODOS
        //objeto de log para uso nos métodos
        Log log = new Log();


        //Lista de categorias
        //public Vm_categoria_old listaCategorias(int conta_id, int usuario_id, int contador_id, Usuario user)
        //{
        //    Vm_categoria_old categoria = new Vm_categoria_old();
        //    List<Vm_categoria_old> caixaBanco = new List<Vm_categoria_old>();
        //    List<Vm_categoria_old> receitas = new List<Vm_categoria_old>();
        //    List<Vm_categoria_old> despesas = new List<Vm_categoria_old>();


        //    try
        //    {
        //        conn.Open();
        //        MySqlCommand comando = new MySqlCommand("SELECT * from contapadrao LEFT join caixabanco on caixabanco.caixaBanco_contaPadrao_id = contapadrao.contaPadrao_id where contapadrao.contaPadrao_status = 'Ativo' and (contapadrao_classificacao LIKE '01.1.1.01.%' or contapadrao_classificacao LIKE '01.1.1.02.%' or contapadrao_classificacao LIKE '03.2.1.01.%' or contapadrao_classificacao LIKE '04.2.1.01.%' or contapadrao_classificacao LIKE '04.2.1.02.%' or contapadrao_classificacao LIKE '04.2.1.03.%') order by contapadrao.contaPadrao_classificacao asc;", conn);
        //        comando.Parameters.AddWithValue("@contador_id", contador_id);
        //        comando.Parameters.AddWithValue("@conta_id", conta_id);

        //        var leitor = comando.ExecuteReader();

        //        if (leitor.HasRows)
        //        {
        //            while (leitor.Read())
        //            {
        //                Vm_categoria_old _categoria = new Vm_categoria_old();
        //                if (DBNull.Value != leitor["contaPadrao_id"])
        //                {
        //                    _categoria.contaPadrao_id = Convert.ToInt32(leitor["contaPadrao_id"]);
        //                }
        //                else
        //                {
        //                    _categoria.contaPadrao_id = 0;
        //                }

        //                if (DBNull.Value != leitor["contaPadrao_conta_id"])
        //                {
        //                    _categoria.contaPadrao_conta_id = Convert.ToInt32(leitor["contaPadrao_conta_id"]);
        //                }
        //                else
        //                {
        //                    _categoria.contaPadrao_conta_id = 0;
        //                }                        
        //                _categoria.contaPadrao_classificacao = leitor["contaPadrao_classificacao"].ToString();
        //                _categoria.contaPadrao_descricao = leitor["contaPadrao_descricao"].ToString();
        //                _categoria.contaPadrao_apelido = leitor["contaPadrao_apelido"].ToString();
        //                _categoria.contaPadrao_grupo = leitor["contaPadrao_grupo"].ToString();
        //                _categoria.contaPadrao_tipo = leitor["contaPadrao_tipo"].ToString();
        //                _categoria.contaPadrao_especie = leitor["contaPadrao_especie"].ToString();
        //                _categoria.contaPadrao_natureza = leitor["contaPadrao_natureza"].ToString();
        //                _categoria.vm_categoria_caixaBanco = leitor["caixaBanco_conta_id"].ToString();
        //                if(DBNull.Value != leitor["contaPadrao_filhos"])
        //                {
        //                    _categoria.contaPadrao_filhos = Convert.ToInt32(leitor["contaPadrao_filhos"]);
        //                }
        //                else
        //                {
        //                    _categoria.contaPadrao_filhos = 0;
        //                }
        //                _categoria.contaPadrao_status = leitor["contaPadrao_status"].ToString();
        //                _categoria.contaPadrao_tags = leitor["contapadrao_tags"].ToString();
        //                _categoria.contaPadrao_codigoBanco = leitor["contaPadrao_codigoBanco"].ToString();
        //                _categoria.caixaBanco_conta_id = leitor["caixaBanco_conta_id"].ToString();

        //                /*----*/

        //                if(_categoria.contaPadrao_grupo.ToUpper() == "RECEITA")
        //                {
        //                    receitas.Add(_categoria);
        //                }
        //                if (_categoria.contaPadrao_grupo.ToUpper() == "DESPESA")
        //                {
        //                    despesas.Add(_categoria);
        //                }

        //                if(_categoria.contaPadrao_classificacao.Contains("01.1.1.01.") || _categoria.caixaBanco_conta_id == conta_id.ToString())
        //                {
        //                    caixaBanco.Add(_categoria);
        //                }
        //            }
        //        }

        //        categoria.caixaBcos = caixaBanco;
        //        categoria.receitas = receitas;
        //        categoria.despesas = despesas;
        //        categoria.userLogado = user;
        //    }
        //    catch (Exception e)
        //    {
        //        string msg = "Tentativa de listar categorias fracassou: " + e.Message.ToString().Substring(0, 300);

        //        //log.log("ContaPadrao", "listaCategorias", "Erro", msg, conta_id, usuario_id);                
        //    }
        //    finally
        //    {
        //        if (conn.State == System.Data.ConnectionState.Open)
        //        {
        //            conn.Close();
        //        }
        //    }

        //    return categoria;
        //}

        ////Busca categoria por id
        //public Vm_categoria_old buscaCategoria(string id, int conta_id, int usuario_id)
        //{
        //    Vm_categoria_old _categoria = new Vm_categoria_old();

        //    try
        //    {
        //        conn.Open();
        //        MySqlCommand comando = new MySqlCommand("SELECT * from contapadrao where contapadrao.contaPadrao_id = @id", conn);                
        //        comando.Parameters.AddWithValue("@id", id);

        //        var leitor = comando.ExecuteReader();

        //        if (leitor.HasRows)
        //        {
        //            while (leitor.Read())
        //            {   
        //                if (DBNull.Value != leitor["contaPadrao_id"])
        //                {
        //                    _categoria.contaPadrao_id = Convert.ToInt32(leitor["contaPadrao_id"]);
        //                }
        //                else
        //                {
        //                    _categoria.contaPadrao_id = 0;
        //                }

        //                if (DBNull.Value != leitor["contaPadrao_conta_id"])
        //                {
        //                    _categoria.contaPadrao_conta_id = Convert.ToInt32(leitor["contaPadrao_conta_id"]);
        //                }
        //                else
        //                {
        //                    _categoria.contaPadrao_conta_id = 0;
        //                }
        //                _categoria.contaPadrao_classificacao = leitor["contaPadrao_classificacao"].ToString();
        //                _categoria.contaPadrao_descricao = leitor["contaPadrao_descricao"].ToString();
        //                _categoria.contaPadrao_apelido = leitor["contaPadrao_apelido"].ToString();
        //                _categoria.contaPadrao_grupo = leitor["contaPadrao_grupo"].ToString();
        //                _categoria.contaPadrao_tipo = leitor["contaPadrao_tipo"].ToString();
        //                _categoria.contaPadrao_especie = leitor["contaPadrao_especie"].ToString();
        //                _categoria.contaPadrao_natureza = leitor["contaPadrao_natureza"].ToString();                        
        //                if (DBNull.Value != leitor["contaPadrao_filhos"])
        //                {
        //                    _categoria.contaPadrao_filhos = Convert.ToInt32(leitor["contaPadrao_filhos"]);
        //                }
        //                else
        //                {
        //                    _categoria.contaPadrao_filhos = 0;
        //                }

Controllers/ContaPadraoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using gestaoContadorcomvc.Models;
using gestaoContadorcomvc.Models.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace gestaoContadorcomvc.Controllers
{
    public class ContaPadraoController : Controller
    {
        // GET: ContaPadraoController
        public ActionResult Index(string pattern)
        {
            ContaPadrao cp = new ContaPadrao();

            ViewData["bread"] = "PLano de contas padrão";

            List<Vm_ContaPadrao> contas = new List<Vm_ContaPadrao>();

            //if(pattern == null)
            //{
            //    contas = cp.listContasPadrao("01");
            //}
            //else
            //{
            //    contas = cp.listContasPadrao(pattern);
            //}

            return View(contas);
        }

        // GET: ContaPadraoController/Create
        public ActionResult Create()
        {
            Selects select = new Selects();
            ViewBag.grupoContas = select.getGrupoContas().Select(c => new SelectListItem() { Text = c.text, Value = c.value, Selected = c.value == "Ativo" }).ToList();

            return View();
        }

        // POST: ContaPadraoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContaPadraoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ContaPadraoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContaPadraoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ContaPadraoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/ContaPadrao/Create.cshtml
@model gestaoContadorcomvc.Models.ViewModel.Vm_ContaPadrao
@{
    Layout = null;
}
<div class="container">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Criar Conta Padrão</h4>
            </div>
            <form asp-controller="ContaPadrao" asp-action="Create">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <p>Cadastrar nova conta no plano de contas padrão</p>
                        </div>
                    </div>
                    <hr class="hrLine" />
                    @{
                        <div class="row">
                            <div class="col-12">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>                                
                                <div class="form-group">
                                    <label asp-for="contaPadrao_classificacao" class="control-label"></label>
                                    <input asp-for="contaPadrao_classificacao" class="form-control" />
                                    <span asp-validation-for="contaPadrao_classificacao" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_descricao" class="control-label"></label>
                                    <input asp-for="contaPadrao_descricao" class="form-control" />
                                    <span asp-validation-for="contaPadrao_descricao" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_apelido" class="control-label"></label>
                                    <input asp-for="contaPadrao_apelido" class="form-control" />
                                    <span asp-validation-for="contaPadrao_apelido" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_grupo" class="control-label"></label>
                                    <select asp-items="@ViewBag.grupoContas" value="@TempData["contaPadrao_grupo"]" name="contaPadrao_grupo" class="form-control"></select>
                                    <span asp-validation-for="contaPadrao_grupo" class="text-danger"></span>
                                </div>
                                @*<div class="form-group">
                                    <label asp-for="contaPadrao_tipo" class="control-label"></label>
                                    <input asp-for="contaPadrao_tipo" class="form-control" />
                                    <span asp-validation-for="contaPadrao_tipo" class="text-danger"></span>
                                </div>*@
                                @*<div class="form-group">
                                    <label asp-for="contaPadrao_conta_id" class="control-label"></label>
                                    <input asp-for="contaPadrao_conta_id" class="form-control" />
                                    <span asp-validation-for="contaPadrao_conta_id" class="text-danger"></span>
                                </div>*@
                                <div class="form-group">
                                    <label asp-for="contaPadrao_especie" class="control-label"></label>
                                    <input asp-for="contaPadrao_especie" class="form-control" />
                                    <span asp-validation-for="contaPadrao_especie" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_natureza" class="control-label"></label>
                                    <input asp-for="contaPadrao_natureza" class="form-control" />
                                    <span asp-validation-for="contaPadrao_natureza" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_filhos" class="control-label"></label>
                                    <input asp-for="contaPadrao_filhos" class="form-control" />
                                    <span asp-validation-for="contaPadrao_filhos" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_status" class="control-label"></label>
                                    <input asp-for="contaPadrao_status" class="form-control" />
                                    <span asp-validation-for="contaPadrao_status" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contapadrao_tags" class="control-label"></label>
                                    <select asp-for="contapadrao_tags" class="form-control">
                                        <option></option>
                                        <option>Geral</option>
                                    </select>                                    
                                    <span asp-validation-for="contapadrao_tags" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_codigoBanco" class="control-label"></label>
                                    <input type="text" asp-for="contaPadrao_codigoBanco" class="form-control" />
                                    <span asp-validation-for="contaPadrao_codigoBanco" class="text-danger"></span>
                                </div>                                
                            </div>
                        </div>
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-info">Gravar</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

Views/ContaPadrao/Edit.cshtml
@model gestaoContadorcomvc.Models.ViewModel.Vm_ContaPadrao
@{
    Layout = null;
}
<div class="container">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Editar Conta Padrão</h4>
            </div>
            <form asp-controller="ContaPadrao" asp-action="Edit">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <p>Alterar conta padrão: <strong>Conta 1</strong></p>
                        </div>
                    </div>
                    <hr class="hrLine" />
                    @{
                        <div class="row">
                            <div class="col-12">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_id" class="control-label"></label>
                                    <input asp-for="contaPadrao_id" class="form-control" />
                                    <span asp-validation-for="contaPadrao_id" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_classificacao" class="control-label"></label>
                                    <input asp-for="contaPadrao_classificacao" class="form-control" />
                                    <span asp-validation-for="contaPadrao_classificacao" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_descricao" class="control-label"></label>
                                    <input asp-for="contaPadrao_descricao" class="form-control" />
                                    <span asp-validation-for="contaPadrao_descricao" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_apelido" class="control-label"></label>
                                    <input asp-for="contaPadrao_apelido" class="form-control" />
                                    <span asp-validation-for="contaPadrao_apelido" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_grupo" class="control-label"></label>
                                    <input asp-for="contaPadrao_grupo" class="form-control" />
                                    <span asp-validation-for="contaPadrao_grupo" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_tipo" class="control-label"></label>
                                    <input asp-for="contaPadrao_tipo" class="form-control" />
                                    <span asp-validation-for="contaPadrao_tipo" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_conta_id" class="control-label"></label>
                                    <input asp-for="contaPadrao_conta_id" class="form-control" />
                                    <span asp-validation-for="contaPadrao_conta_id" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_especie" class="control-label"></label>
                                    <input asp-for="contaPadrao_especie" class="form-control" />
                                    <span asp-validation-for="contaPadrao_especie" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_natureza" class="control-label"></label>
                                    <input asp-for="contaPadrao_natureza" class="form-control" />
                                    <span asp-validation-for="contaPadrao_natureza" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_filhos" class="control-label"></label>
                                    <input asp-for="contaPadrao_filhos" class="form-control" />
                                    <span asp-validation-for="contaPadrao_filhos" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_status" class="control-label"></label>
                                    <input asp-for="contaPadrao_status" class="form-control" />
                                    <span asp-validation-for="contaPadrao_status" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contapadrao_tags" class="control-label"></label>
                                    <input asp-for="contapadrao_tags" class="form-control" />
                                    <span asp-validation-for="contapadrao_tags" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="contaPadrao_codigoBanco" class="control-label"></label>
                                    <input asp-for="contaPadrao_codigoBanco" class="form-control" />
                                    <span asp-validation-for="contaPadrao_codigoBanco" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-info">Gravar</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

Views/ContaPadrao/Index.cshtml
@model IEnumerable<gestaoContadorcomvc.Models.ViewModel.Vm_ContaPadrao>

<style>
    .tab_2 {
        padding-left: 0px;
    }

    .tab_4 {
        padding-left: 10px;
    }

    .tab_6 {
        padding-left: 20px;
    }

    .tab_9 {
        padding-left: 30px;
    }

    .tab_13 {
        padding-left: 40px;
    }

    .tab_22 {
        padding-left: 50px;
    }

    .container {
        max-width: 100%;
    }

    .col-list-left label {
        display: none;
    }

    .Deletado {
        background-color: #f08d8d;
    }
</style>



<h2>Plano de Contas Padrão</h2>
<hr class="hrLine" />


<button class="btn btn-info" style="margin-bottom:10px;" asp-controller="ContaPadrao" asp-action="Index" data-id="nova"><a class="createConta" data-id="novaCategoria" style="cursor:pointer">Cadastrar nova conta</a></button>


<form asp-controller="ContaPadrao" asp-action="Index">
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Pequisa por classificação" aria-label="Pequisa por classificação" aria-describedby="button-addon2" name="pattern">
        <div class="input-group-append">
            <button class="btn btn-outline-info" type="submit">Buscar</button>
        </div>
    </div>
</form>

<div class="line-list line-list-head">
    <div class="col-list-left">
        <input class="check-list-input" type="checkbox" id="cp_todas">
        <label class="check-list-label" for="cp_todas"></label>
    </div>
    <div class="col-list-body">
        <div class="row">
            @*<div class="col-12 col-md-2">
                    <span><strong>Classificação</strong></span>
                </div>*@
            <div class="col-12 col-md-8">
                <span><strong>Nome</strong></span>
            </div>
            <div class="col-12 col-md-1">
                <span><strong>Tipo</strong></span>
            </div>
            <div class="col-12 col-md-1">
                <span><strong>Cliente</strong></span>
            </div>
            <div class="col-12 col-md-1">
                <span><strong>Situação</strong></span>
            </div>
            <div class="col-12 col-md-1">

            </div>
        </div>
    </div>
    @*<div class="col-list-rigth" style="padding-right: 10px;">
            <span><strong>Ações</strong></span>
        </div>*@
</div>

@{
    foreach (var item in Model)
    {
        <div class="line-list @item.contaPadrao_status">
            <div class="col-list-left">
                <input class="check-list-input" type="checkbox" id="cp_@item.contaPadrao_id">
                <label class="check-list-label" for="cp_@Html.DisplayFor(modelItem => item.contaPadrao_id)"></label>
            </div>
            <div class="col-list-body">
                <div class="row">
                    @*<div class="col-12 col-md-2">
                            <span>@Html.DisplayFor(modelItem => item.contaPadrao_classificacao)</span>
                        </div>*@
                    <div class="col-12 col-md-8">
                        <span class="tab_@item.contaPadrao_classificacao.Length"><span>@Html.DisplayFor(modelItem => item.contaPadrao_classificacao)</span>. @Html.DisplayFor(modelItem => item.contaPadrao_descricao)</span>
                    </div>
                    <div class="col-12 col-md-1">
                        <span>@Html.DisplayFor(modelItem => item.contaPadrao_tipo)</span>
                    </div>
                    <div class="col-12 col-md-1">
                        @{
                            if (item.contaPadrao_conta_id > 0)
                            {
                                <span>@Html.DisplayFor(modelItem => item.contaPadrao_conta_id)</span>
                            }
                        }
                    </div>
                    <div class="col-12 col-md-1">
                        <span>@Html.DisplayFor(modelItem => item.contaPadrao_status)</span>
                    </div>
                    <div class="col-12 col-md-1">

                    </div>
                </div>
            </div>
            <div class="col-list-rigth">
                <a class="edit" data-id="@item.contaPadrao_id" style="cursor:pointer">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                    </svg>
                </a>
            </div>
        </div>
    }
}

<div class="row" style="margin-bottom: 10px;margin-top:10px;"></div>

<div id="modal" class="modal fade" role="dialog" />