Controllers/ContaCorrenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using gestaoContadorcomvc.Filtros;
using gestaoContadorcomvc.Models;
using gestaoContadorcomvc.Models.Autenticacao;
using gestaoContadorcomvc.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace gestaoContadorcomvc.Controllers
{
    [Authorize]
    public class ContaCorrenteController : Controller
    {
        [Autoriza(permissao = "ccorrenteList")]
        public ActionResult Index()
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);

            ContaCorrente ccorrente = new ContaCorrente();
            Vm_conta_corrente vm_corrente = new Vm_conta_corrente();

            vm_corrente.contas_corrente = ccorrente.listContaCorrete(user.usuario_conta_id, user.usuario_id);
            vm_corrente.user = user;

            return View(vm_corrente);
        }

        [Autoriza(permissao = "ccorrenteCreate")]
        public ActionResult Create()
        {
            Selects select = new Selects();
            ViewBag.tipoContaCorrente = select.getTiposContaCorrente().Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled, Selected = c.value == "1" });

            Vm_conta_corrente vm_ccorrente = new Vm_conta_corrente();
            vm_ccorrente.ccorrente_saldo_abertura = 0;

            return View(vm_ccorrente);
        }

        // POST: ContaCorrenteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection d)
        {
            ContaCorrente ccorrente = new ContaCorrente();
            Vm_conta_corrente vm_corrente = new Vm_conta_corrente();

            Selects select = new Selects();
            ViewBag.tipoContaCorrente = select.getTiposContaCorrente().Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled, Selected = c.value == "1" });

            try
            {
                Usuario usuario = new Usuario();
                Vm_usuario user = new Vm_usuario();
                user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);


                vm_corrente.ccorrente_nome = d["ccorrente_nome"];
                vm_corrente.ccorrente_tipo = d["ccorrente_tipo"];
                vm_corrente.ccorrente_saldo_abertura = Convert.ToDecimal(d["ccorrente_saldo_abertura"]);
                vm_corrente.ccorrente_masc_contabil = d["ccorrente_masc_contabil"];

                if (!ModelState.IsValid)
                {
                    TempData["msgCCorrente"] = "Formulário com informação incorreta (Erro)!";

                    return View(vm_corrente);
                }

                TempData["msgCCorrente"] = ccorrente.cadastraContaCorrente(user.usuario_conta_id, user.usuario_id, vm_corrente.ccorrente_nome, vm_corrente.ccorrente_tipo, vm_corrente.ccorrente_masc_contabil, vm_corrente.ccorrente_saldo_abertura);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["msgCCorrente"] = "Erro na gravação dos dados da conta corrente!";

                return View(vm_corrente);
            }
        }

        [Autoriza(permissao = "ccorrenteEdit")]
        public ActionResult Edit(int id)
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);

            ContaCorrente ccorrente = new ContaCorrente();
            Vm_conta_corrente vm_corrente = new Vm_conta_corrente();

            vm_corrente = ccorrente.buscaContaCorrete(user.usuario_conta_id, user.usuario_id, id);

            Selects select = new Selects();
            ViewBag.tipoContaCorrente = select.getTiposContaCorrente().Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled, Selected = c.value == vm_corrente.ccorrente_tipo });
            ViewBag.status = select.getStatus().Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled, Selected = c.value == vm_corrente.ccorrente_status });


            return View(vm_corrente);
        }

        // POST: ContaCorrenteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int ccorrente_id, IFormCollection d)
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);

            ContaCorrente ccorrente = new ContaCorrente();
            Vm_conta_corrente vm_corrente = new Vm_conta_corrente();

            Selects select = new Selects();
            ViewBag.tipoContaCorrente = select.getTiposContaCorrente().Select(c => new SelectListItem() { Text = c.text, Value = c.value, Disabled = c.disabled, Selected = c.value == d["ccorrente_status"] });
                        
            vm_corrente.ccorrente_nome = d["ccorrente_nome"];
            vm_corrente.ccorrente_tipo = d["ccorrente_tipo"];
            vm_corrente.ccorrente_saldo_abertura = Convert.ToDecimal(d["ccorrente_saldo_abertura"]);
            vm_corrente.ccorrente_masc_contabil = d["ccorrente_masc_contabil"];
            vm_corrente.ccorrente_status = d["ccorrente_status"];
            vm_corrente.ccorrente_id = ccorrente_id;


            if (!ModelState.IsValid)
            {
                TempData["msgCCorrente"] = "Formulário com informação incorreta (Erro)!";

                return View(vm_corrente);
            }

            TempData["msgCCorrente"] = ccorrente.alteraContaCorrente(user.usuario_conta_id,user.usuario_id,vm_corrente.ccorrente_nome,vm_corrente.ccorrente_tipo,vm_corrente.ccorrente_masc_contabil,vm_corrente.ccorrente_saldo_abertura,vm_corrente.ccorrente_status,ccorrente_id); ;

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["msgCCorrente"] = "Erro na gravação dos dados da conta corrente!";

                return View(vm_corrente);
            }
        }

        [Autoriza(permissao = "ccorrenteDelete")]
        public ActionResult Delete(int id)
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);

            ContaCorrente ccorrente = new ContaCorrente();
            Vm_conta_corrente vm_corrente = new Vm_conta_corrente();

            vm_corrente = ccorrente.buscaContaCorrete(user.usuario_conta_id, user.usuario_id, id);        


            return View(vm_corrente);
        }

        // POST: ContaCorrenteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int ccorrente_id, IFormCollection collection)
        {
            try
            {
                Usuario usuario = new Usuario();
                Vm_usuario user = new Vm_usuario();
                user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);

                ContaCorrente ccorrente = new ContaCorrente();
                Vm_conta_corrente vm_corrente = new Vm_conta_corrente();

                TempData["msgCCorrente"] = ccorrente.deleteContaCorrente(user.usuario_conta_id, user.usuario_id, ccorrente_id);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["msgProdutos"] = "Erro ao tentar apagar a conta corrente!";

                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult gerarContasCorrentes_ajax(string[] tipo)
        {
            Usuario usuario = new Usuario();
            Vm_usuario user = new Vm_usuario();
            user = usuario.BuscaUsuario(HttpContext.User.Identity.Name);

            Selects select = new Selects();
            List<Selects> lista = new List<Selects>();

            lista = select.getContasCorrenteConta_id(user.conta.conta_id);

            return Json(JsonConvert.SerializeObject(lista));
        }
    }
}

Views/ContaCorrente/Create.cshtml
@model gestaoContadorcomvc.Models.ViewModel.Vm_conta_corrente

@{
    ViewData["Title"] = "Conta Corrente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (TempData["msgCCorrente"] != null && TempData["msgCCorrente"].ToString().Contains("sucesso"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Sucesso!</strong> @TempData["msgCCorrente"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    if (TempData["msgCCorrente"] != null && TempData["msgCCorrente"].ToString().Contains("Erro"))
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Erro!</strong> @TempData["msgCCorrente"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<h2>Nova Conta Corrente</h2>
<hr class="hrLine" />

<form asp-controller="ContaCorrente" asp-action="Create" id="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-12 col-md-8">
            <div class="form-group">
                <label asp-for="ccorrente_nome" class="control-label"></label>
                <input asp-for="ccorrente_nome" class="form-control" />
                <span asp-validation-for="ccorrente_nome" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_status" class="control-label"></label>
                <input asp-for="ccorrente_status" class="form-control" value="Ativo" readonly="readonly" />
                <span asp-validation-for="ccorrente_status" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_tipo" class="control-label"></label>
                <select asp-items="@ViewBag.tipoContaCorrente" value="@TempData["ccorrente_tipo"]" id="ccorrente_tipo" name="ccorrente_tipo" class="form-control"></select>
                <span asp-validation-for="ccorrente_tipo" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_saldo_abertura" class="control-label"></label>
                <input type="text" value="@Model.ccorrente_saldo_abertura" id="ccorrente_saldo_abertura" name="ccorrente_saldo_abertura" class="form-control" onblur="decimal(this.id, this.value, '2')" />
                <span asp-validation-for="ccorrente_saldo_abertura" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_masc_contabil" class="control-label"></label>
                <input asp-for="ccorrente_masc_contabil" class="form-control" />
                <span asp-validation-for="ccorrente_masc_contabil" class="text-danger"></span>
            </div>
        </div>
    </div>

    <br />

    <button type="submit" class="btn btn-info" id="sub_form" onclick="blockSubmit(this.id,'form')">Gravar</button>
    <a class="btn btn-secondary" asp-controller="ContaCorrente" asp-action="Index">Cancelar</a>
    <br /><span class="text-info" id="msg_blockSubmit"></span>

</form>

Views/ContaCorrente/Delete.cshtml
@model gestaoContadorcomvc.Models.ViewModel.Vm_conta_corrente
@{
    Layout = null;
}

<div class="container">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Confirmação de Exclusão</h4>
            </div>
            <div class="modal-body">
                <p>Confirme a exclusão da conta corrente: </p>
                <p><strong>Nome: </strong>@Model.ccorrente_nome</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <form asp-controller="ContaCorrente" asp-action="Delete">
                    <input type="hidden" value="@Model.ccorrente_id" name="ccorrente_id" />
                    <button type="submit" class="btn btn-info">Apagar</button>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

Views/ContaCorrente/Edit.cshtml
@model gestaoContadorcomvc.Models.ViewModel.Vm_conta_corrente

@{
    ViewData["Title"] = "Conta Corrente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (TempData["msgCCorrente"] != null && TempData["msgCCorrente"].ToString().Contains("sucesso"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Sucesso!</strong> @TempData["msgCCorrente"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    if (TempData["msgCCorrente"] != null && TempData["msgCCorrente"].ToString().Contains("Erro"))
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Erro!</strong> @TempData["msgCCorrente"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<h2>Alterar Conta Corrente</h2>
<hr class="hrLine" />

<form asp-controller="ContaCorrente" asp-action="Edit" id="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-12 col-md-8">
            <div class="form-group">
                <label asp-for="ccorrente_nome" class="control-label"></label>
                <input asp-for="ccorrente_nome" class="form-control" />
                <span asp-validation-for="ccorrente_nome" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_status" class="control-label"></label>
                <select asp-items="@ViewBag.status" value="@TempData["ccorrente_status"]" id="ccorrente_status" name="ccorrente_status" class="form-control"></select>
                <span asp-validation-for="ccorrente_status" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_tipo" class="control-label"></label>
                <select asp-items="@ViewBag.tipoContaCorrente" value="@TempData["ccorrente_tipo"]" id="ccorrente_tipo" name="ccorrente_tipo" class="form-control"></select>
                <span asp-validation-for="ccorrente_tipo" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_saldo_abertura" class="control-label"></label>
                <input type="text" value="@Model.ccorrente_saldo_abertura.ToString("N2")" id="ccorrente_saldo_abertura" name="ccorrente_saldo_abertura" class="form-control" onblur="decimal(this.id, this.value, '2')" />
                <span asp-validation-for="ccorrente_saldo_abertura" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="form-group">
                <label asp-for="ccorrente_masc_contabil" class="control-label"></label>
                <input asp-for="ccorrente_masc_contabil" class="form-control" />
                <span asp-validation-for="ccorrente_masc_contabil" class="text-danger"></span>
            </div>
        </div>
    </div>

    <input type="hidden" asp-for="ccorrente_id" />

    <br />

    <button type="submit" class="btn btn-info" id="sub_form" onclick="blockSubmit(this.id,'form')">Gravar</button>
    <a class="btn btn-secondary" asp-controller="ContaCorrente" asp-action="Index">Cancelar</a>
    <br /><span class="text-info" id="msg_blockSubmit"></span>

</form>

Views/ContaCorrente/Index.cshtml
@model gestaoContadorcomvc.Models.ViewModel.Vm_conta_corrente

@{
    ViewData["Title"] = "Conta Corrente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .col-list-rigth {
        width: 90px;
        text-align: right;
    }

    .check-list-label {
        display: none;
    }

    .col-list-body {
        width: calc(100% - 90px);
    }

    a {
        cursor: pointer;
    }

    .line-list {
        border: 0px;
    }
</style>

@{
    if (TempData["msgCCorrente"] != null && TempData["msgCCorrente"].ToString().Contains("sucesso"))
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Sucesso!</strong> @TempData["msgCCorrente"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    if (TempData["msgCCorrente"] != null && TempData["msgCCorrente"].ToString().Contains("Erro"))
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert" id="Esconder">
            <strong>Erro!</strong> @TempData["msgCCorrente"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<h2>Conta Corrente</h2>
<hr class="hrLine" />

@{
    if (Model.user.Role.Equals("adm") || Model.user._permissoes.ccorrenteCreate)
    {
        <a class="btn btn-info" style="margin-bottom:10px;" asp-controller="ContaCorrente" asp-action="Create">Novo</a>
    }

    //Cabeçalho
    <div class="list-header">
        <div class="line-list">
            <div class="col-list-left">
                <input class="check-list-input" type="checkbox" id="cp_todas">
                <label class="check-list-label" for="cp_todas"></label>
            </div>
            <div class="col-list-body">
                <div class="row">
                    <div class="col-12 col-md-7"><strong>Nome</strong></div>
                    <div class="col-12 col-md-3"><strong>Tipo</strong></div>
                    <div class="col-12 col-md-2" style="white-space:nowrap"><strong>Conta Contábil</strong></div>
                </div>
            </div>
            <div class="col-list-rigth" style="padding-right: 10px;">
                <span><strong>Ações</strong></span>
            </div>
        </div>
    </div>

    foreach (var item in Model.contas_corrente)
    {
        <div class="line-list">
            <div class="col-list-left">
                <input class="check-list-input" type="checkbox" id="cp_todas">
                <label class="check-list-label" for="cp_todas"></label>
            </div>
            <div class="col-list-body">
                <div class="row">
                    <div class="col-12 line_list_title_mobile"><strong>Nome: </strong>@item.ccorrente_nome</div>
                    <div class="col-12 line_list_title_mobile"><strong>Tipo: </strong>@item.ccorrente_tipo</div>                    
                    <div class="col-12 line_list_title_mobile"><strong>Conta Contábil: </strong>@item.ccorrente_masc_contabil</div>                    

                    <div class="col-7 line_list_title_full">@item.ccorrente_nome</div>
                    <div class="col-3 line_list_title_full">@item.ccorrente_tipo</div>                    
                    <div class="col-2 line_list_title_full">@item.ccorrente_masc_contabil</div>                    
                </div>
            </div>
            <div class="col-list-rigth" style="padding-right: 10px;">
                @{
                    if (Model.user.Role == "adm" || Model.user._permissoes.ccorrenteEdit)
                    {
                        <a asp-controller="ContaCorrente" asp-action="Edit" asp-route-id="@item.ccorrente_id">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                            </svg>
                        </a>
                    }
                    if (Model.user.Role == "adm" || Model.user._permissoes.ccorrenteDelete)
                    {
                        <a class="delete" data-id="@item.ccorrente_id">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                            </svg>
                        </a>
                    }
                }
            </div>
        </div>
    }


}